<?php

/**
 * @file
 * Alter drupal site administrator form and creating JSON API.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uc_quickpay_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  // Alter submit button on site config setting form from admin side.
  $form['actions']['submit']['#value'] = t('Update Configuration');
}
